name: 'tf deploy to azure'

on: 
  push: 
    branches:
    - main
env: 
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
  
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production
    defaults: 
      run:
        shell: bash
    
    steps:
    - name: checkout
      uses: actions/checkout@v2
      
    - name: Setup terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    
    - name: terraform init
      run: terraform init
    
    - name: terraform format
      run: terraform fmt -check
      
    - name: terraform plan
      run: terraform plan
