name: Terraform deployment
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "sam_lab" branch
  push:
    branches: [ "main" ]
    # paths:
    #   - "src/**"
      # - ".github/workflows/uat.yml"
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env: 
  ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
# Modify default permissions granted to GITHUB_TOKEN
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: path check
          run: |
            pwd
            ls -a
        - name: Terraform Version 
          run: terraform version 

        - name: 'Terraform Format'
          uses: hashicorp/terraform-github-actions@master
          with:
            tf_actions_version: 1.4.6
            tf_actions_subcommand: 'fmt'
            tf_actions_working_dir: "./terraform"
