name: Terraform deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "sam_lab" branch
  push:
    branches: [ "main" ]
    # paths:
    #   - "src/**"
      # - ".github/workflows/uat.yml"



  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env: 
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  #ROOT_PATH: '${{github.workspace}}/terraform'
# Modify default permissions granted to GITHUB_TOKEN
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: setup terraform
          uses: hashicorp/setup-terraform@v2.0.3
          with:
            cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
        
        - run: terraform init

        - run: terraform plan


        # - name: 'Terraform Plan'
        #   uses: hashicorp/terraform-github-actions@master
        #   with:
        #     tf_actions_version: 1.4.6
        #     tf_actions_subcommand: 'plan'
            # tf_actions_working_dir: "./terraform"

        # - name: az login test
        #   run: az --version

        # - name: az login test
        #   run: az --version

        # - name: 'Terraform Init'
        # uses: hashicorp/terraform-github-actions@master
        # with:
        #   tf_actions_version: 1.4.6
        #   tf_actions_subcommand: 'init'
        #   #tf_actions_working_dir: ${{env.ROOT_PATH}}
        #   tf_actions_comment: true

  
  # # This workflow contains a single job called "deploy"
  # deploy:
  #   # The type of runner that the job will run on
    # runs-on: ubuntu-latest
  
    # steps:
    #   - name: Checkout code
    #     uses: actions/checkout@v3
  #     - name: "Azure Login"
  #       run: azlogin

  #     - name: "Build & Push Image"
  #       run: |
  #         buildctl --addr tcp://buildkitd:1234 build --frontend=dockerfile.v0 --local context=. --local dockerfile=. --output type=image,name=${IMAGE_REGISTRY}/${IMAGE_REPOSITORY}:${IMAGE_TAG},push=true

  #     # - name: "Build Image"
  #     #   run: |
  #     #     buildctl --addr tcp://buildkitd:1234 build --frontend=dockerfile.v0 --local context=. --local dockerfile=. --output type=image,name=${IMAGE_REGISTRY}/${IMAGE_REPOSITORY}:${IMAGE_TAG}
